version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:3000
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: node_login_microservice
    # disabled for nginx mode
    # container_name: nodejs_api
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: mysql://aniket:password@mysql:3306/userdb
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    hostname: mysqlcontainer
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=aniket
      - MYSQL_PASSWORD=password
