# FROM arm64v8/python:latest

# WORKDIR /app

# COPY . /app

# RUN pip3 install -r requirements.txt

# RUN pip install --no-cache-dir -r requirements.txt

# EXPOSE 4000

# CMD [ "python3", "-m" , "flask", "run", "--host" ,"0.0.0.0", "--port", "4000"]

# Use an official Python runtime as the parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=4000

# Expose port 4000 to the host
EXPOSE 4000

# Run the command to start the service
CMD ["flask", "run"]
